name: iyox_wormhole
version: 0.2.5+47
homepage: https://github.com/iyox-studios/iyox-Wormhole/
publish_to: none
environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.27.0"
description: Mobile Client for the magic-wormhole protocol
dependencies:
  animations: ^2.0.11
  archive: ^4.0.5
  device_info_plus: ^11.3.0
  dynamic_color: ^1.7.0
  file_picker: ^9.0.2
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.1.0
  flutter_displaymode: ^0.6.0
  flutter_localizations:
    sdk: flutter
  flutter_localized_locales: ^2.0.5
  flutter_rust_bridge: 2.8.0
  flutter_svg: ^2.0.17
  freezed_annotation: ^2.4.4
  go_router: ^14.8.1
  icons_launcher: ^3.0.1
  logger: ^2.5.0
  package_info_plus: ^8.0.0
  path_provider: ^2.1.5
  permission_handler: ^10.4.5
  pick_or_save:
    git: https://github.com/EwuUwe/pick_or_save
  qr_code_scanner_plus: ^2.0.10+1
  qr_flutter: ^4.1.0
  receive_sharing_intent:
    git: https://github.com/KasemJaffer/receive_sharing_intent
  rust_lib_iyox_wormhole:
    path: rust_builder
  shared_preferences: ^2.5.2
  slang: ^4.5.0
  slang_flutter: ^4.5.0
  uri_content: ^3.0.0
  vibration: ^3.1.3
dev_dependencies:
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  freezed: ^2.5.8
  slang_build_runner: ^4.5.0
flutter:
  uses-material-design: true
  assets:
    - assets/illustrations/
